doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            DomainUser:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/User/Entity'
                prefix: 'App\Domain\User\Entity'
                alias: DomainUser
            DomainHealth:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Health/Entity'
                prefix: 'App\Domain\Health\Entity'
                alias: DomainHealth
            DomainCharacter:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Character/Entity'
                prefix: 'App\Domain\Character\Entity'
                alias: DomainCharacter
            DomainTraining:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Training/Entity'
                prefix: 'App\Domain\Training\Entity'
                alias: DomainTraining
            DomainSkill:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Skill/Entity'
                prefix: 'App\Domain\Skill\Entity'
                alias: DomainSkill
            DomainInventory:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Inventory/Entity'
                prefix: 'App\Domain\Inventory\Entity'
                alias: DomainInventory
            DomainMedia:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Media/Entity'
                prefix: 'App\Domain\Media\Entity'
                alias: DomainMedia
            DomainConfig:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Config/Entity'
                prefix: 'App\Domain\Config\Entity'
                alias: DomainConfig
            DomainMob:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Mob/Entity'
                prefix: 'App\Domain\Mob\Entity'
                alias: DomainMob
            DomainActivity:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Activity/Entity'
                prefix: 'App\Domain\Activity\Entity'
                alias: DomainActivity
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # SQLite URL comes from .env.test
            dbname_suffix: ''

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
